yarnPath: .yarn/releases/yarn-3.3.0.cjs

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}
